name: "Install Deps"
description: "Installs projects dependencies"
runs:
  using: "composite"
  steps:
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "npm"
    - name: Install deps
      shell: bash
      run: npm ci
