on:
  workflow_call:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install deps
        run: npm ci
